spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mint
    username: root
    password: PythA90ra5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#server:
#  tomcat:
#    accesslog:
#      enabled: true
##    basedir: target/tomcat